version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slink-app
    environment:
      APP_URL: ${APP_URL}
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_SECRET: ${APP_SECRET}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: unless-stopped
  db:
    image: mariadb:10.11
    container_name: slink-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
volumes:
  db_data:
