version: "3.8"
services:
  app:
    # Utiliser l'image officielle depuis Docker Hub
    image: slinkapp/slink:latest
    container_name: slink-app
    environment:
      # Configuration de base
      APP_ENV: prod
      APP_DEBUG: "false"
      APP_URL: ${APP_URL}
      APP_SECRET: ${APP_SECRET}
      
      # Configuration base de données
      DATABASE_URL: "mysql://${DB_USERNAME}:${DB_PASSWORD}@db:3306/${DB_DATABASE}"
      
      # Configuration PHP
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-512M}
      
      # Configuration Slink spécifique
      STORAGE_PROVIDER: local
      MAX_UPLOAD_SIZE: 50M
      
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - slink_storage:/var/www/html/storage
      - slink_uploads:/var/www/html/public/uploads
    restart: unless-stopped

  db:
    image: mariadb:10.11
    container_name: slink-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
  slink_storage:
  slink_uploads:
